# Generated by Django 5.0.4 on 2025-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Office"), (2, "Transport")], default=1
            ),
        ),
    ]
