# Generated by Django 5.0.4 on 2025-09-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.RemoveField(
            model_name="employeestatus",
            name="absence_status",
        ),
        migrations.RemoveField(
            model_name="employeestatus",
            name="sick_leaves_days",
        ),
        migrations.RemoveField(
            model_name="employeestatus",
            name="sick_leaves_days_taken",
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="annual_leave_period",
            field=models.CharField(
                help_text="Period of annual leave mark like 10/06/26-24/06/26",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="medical_leave_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of working days in medical leave period given by doctor",
            ),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="medical_leave_period",
            field=models.CharField(
                help_text="Period of medical leave days", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="presence_status",
            field=models.BooleanField(
                default=True, help_text="Is employee available at given date"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="billing_address",
            field=models.CharField(
                blank=True,
                help_text="Billing address ",
                max_length=100,
                null=True,
                verbose_name="Billing Address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Primary contact email use to create user account",
                max_length=50,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                help_text="Contact phone number",
                max_length=11,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                help_text="Office or Garage in which employee will work",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="driver",
            field=models.BooleanField(
                default=False, help_text="Driver License Category 'C'"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="driver_semi",
            field=models.BooleanField(
                default=False, help_text="Driver License Category 'CE"
            ),
        ),
        migrations.AlterField(
            model_name="employeestatus",
            name="absence_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of absence days this year"
            ),
        ),
        migrations.AlterField(
            model_name="employeestatus",
            name="on_route",
            field=models.BooleanField(
                default=False, help_text="Working on current task"
            ),
        ),
    ]
