# Generated by Django 5.0.4 on 2025-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
