# Generated by Django 5.0.4 on 2025-09-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_department_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="annual_leave_days",
            field=models.PositiveIntegerField(
                default=26, help_text="Number of annual leave days"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="driver",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AnnualLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "days_count",
                    models.PositiveIntegerField(
                        help_text="Number of working days of leave"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for leave (optional)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="users.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_leaves",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Leave",
                "verbose_name_plural": "Annual Leaves",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SickLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "days_count",
                    models.PositiveIntegerField(help_text="Number of sick leave days"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sick_leaves",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sick Leave",
                "verbose_name_plural": "Sick Leaves",
                "ordering": ["-start_date"],
            },
        ),
    ]
