# Generated by Django 5.0.4 on 2025-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_client_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeestatus",
            old_name="on_route",
            new_name="task_in_progress",
        ),
        migrations.RemoveField(
            model_name="employeestatus",
            name="annual_leave_period",
        ),
        migrations.RemoveField(
            model_name="employeestatus",
            name="medical_leave_period",
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="annual_leave_end",
            field=models.DateTimeField(
                blank=True, help_text="End date of annual leave period", null=True
            ),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="annual_leave_start",
            field=models.DateTimeField(
                blank=True, help_text="Start date of annual leave period", null=True
            ),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="medical_leave_end",
            field=models.CharField(
                help_text="Period of medical leave end date", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="medical_leave_start",
            field=models.CharField(
                help_text="Period of medical leave start date", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="years_of_work",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of years of work for annual leave counting"
            ),
        ),
        migrations.AlterField(
            model_name="employeestatus",
            name="annual_leave_days_total",
            field=models.PositiveIntegerField(
                default=20, help_text="Number of annual leave days", null=True
            ),
        ),
    ]
