# Generated by Django 5.0.4 on 2025-09-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_employee_annual_leave_days_alter_employee_driver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sickleave",
            name="employee",
        ),
        migrations.DeleteModel(
            name="AnnualLeave",
        ),
        migrations.DeleteModel(
            name="SickLeave",
        ),
    ]
