# Generated by Django 5.0.4 on 2025-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_on_route_employeestatus_task_in_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Office"), (2, "Transport")], default=2
            ),
        ),
    ]
