# Generated by Django 5.0.4 on 2025-07-29 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Distance"
                    ),
                ),
                (
                    "total_duration",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Duration"
                    ),
                ),
                (
                    "transport_distance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Transport Distance",
                    ),
                ),
                (
                    "transport_duration",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Transport Duration",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "collection_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Collection Date"
                    ),
                ),
                (
                    "collection_address",
                    models.CharField(
                        help_text="Collection address",
                        max_length=100,
                        verbose_name="Collection Address",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        help_text="Delivery address",
                        max_length=100,
                        verbose_name="Delivery Address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CargoTransportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Pending acceptance"),
                            (2, "Accepted"),
                            (3, "In progress"),
                            (4, "Completed"),
                            (5, "Rejected"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CargoDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.FloatField(
                        help_text="length of the cargo bed in centimeters",
                        verbose_name="Length",
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        help_text="width  of the cargo bed in centimeters",
                        verbose_name="Width",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        help_text="height of the cargo bed in centimeters",
                        verbose_name="Height",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        help_text="Gross Vehicle Weight in Kilograms",
                        verbose_name="Weight",
                    ),
                ),
                (
                    "cargo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="cargos.cargotransport",
                        verbose_name="Cargo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cargotransport",
            name="cargo_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cargos.cargotransportstatus",
            ),
        ),
    ]
