# Generated by Django 5.0.4 on 2025-08-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cargos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cargotransportstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cargotransport",
            name="cargo_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cargos.cargotransportstatus",
            ),
        ),
    ]
