# Generated by Django 5.0.4 on 2025-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargotransport",
            name="notes",
            field=models.CharField(
                blank=True,
                max_length=900,
                null=True,
                verbose_name="Additional information",
            ),
        ),
    ]
