# Generated by Django 5.0.4 on 2025-09-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0003_cargotransport_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargotransport",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="About cargo, loading and unloading place",
                max_length=900,
                null=True,
                verbose_name="Additional information",
            ),
        ),
    ]
