STATUS_PENDING_ACCEPTANCE = 1
STATUS_ACCEPTED = 2
STATUS_IN_PROGRESS = 3
STATUS_COMPLETED = 4
STATUS_REJECTED = 5

STATUS = [
        STATUS_PENDING_ACCEPTANCE,
        STATUS_ACCEPTED,
        STATUS_IN_PROGRESS,
        STATUS_COMPLETED,
        STATUS_REJECTED,
        ]
