# Generated by Django 5.0.4 on 2025-10-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Tractor", "Tractor"),
                            ("Solo", "Solo Truck"),
                            ("Semi-trailer", "Semi-trailer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("plates", models.CharField(max_length=20, unique=True)),
                (
                    "connected_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "Tractor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_trailers",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.FloatField(
                        help_text="length of the cargo bed in centimeters"
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        help_text="width  of the cargo bed in centimeters"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        help_text="height of the cargo bed in centimeters"
                    ),
                ),
                (
                    "payload_capacity",
                    models.FloatField(
                        help_text="Gross Vehicle Weight in Kilograms",
                        verbose_name="GVW",
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
