# Generated by Django 5.0.4 on 2025-10-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="connected_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The attached semi-trailer.",
                limit_choices_to={"type": "tractor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_trailers",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="department",
            field=models.ForeignKey(
                help_text="The department this vehicle belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plates",
            field=models.CharField(
                help_text="The register plates of the vehicle.",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("tractor", "Tractor"),
                    ("solo_truck", "Solo Truck"),
                    ("semi_trailer", "Semi-trailer"),
                ],
                help_text="The type of vehicle.",
                max_length=30,
            ),
        ),
    ]
