# Generated by Django 5.0.4 on 2025-11-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transports", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="transport_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport",
                to="transports.transportstatus",
            ),
        ),
    ]
