# Generated by Django 5.0.4 on 2025-10-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0003_alter_transport_driver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transport",
            old_name="cargo_status",
            new_name="transport_status",
        ),
    ]
