# Generated by Django 5.0.4 on 2025-08-20 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cargos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("delivery_date", models.DateTimeField()),
                ("transport_duration", models.FloatField()),
                ("total_duration", models.FloatField()),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cargos.cargotransport",
                    ),
                ),
            ],
        ),
    ]
