# Generated by Django 5.0.4 on 2025-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnualLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "days_count",
                    models.PositiveIntegerField(
                        help_text="Number of working days of leave"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for leave (optional)"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default=1,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Annual Leave",
                "verbose_name_plural": "Annual Leaves",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("delivery_date", models.DateTimeField()),
                ("transport_duration", models.FloatField()),
                ("total_duration", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SickLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "days_count",
                    models.PositiveIntegerField(help_text="Number of sick leave days"),
                ),
            ],
            options={
                "verbose_name": "Sick Leave",
                "verbose_name_plural": "Sick Leaves",
                "ordering": ["-start_date"],
            },
        ),
    ]
