# Generated by Django 5.0.4 on 2025-07-29 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cargos", "0001_initial"),
        ("schedules", "0001_initial"),
        ("users", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.department"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.employee"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cargos.cargotransportstatus",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="vehicle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle"
            ),
        ),
    ]
