# Generated by Django 5.0.4 on 2025-09-16 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedules", "0001_initial"),
        ("transport", "0001_initial"),
        ("users", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualleave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to="users.employee",
            ),
        ),
        migrations.AddField(
            model_name="annualleave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_leaves",
                to="users.employee",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="transport.transport"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.department"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.employee"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transport.transportstatus",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="vehicle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle"
            ),
        ),
        migrations.AddField(
            model_name="sickleave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sick_leaves",
                to="users.employee",
            ),
        ),
    ]
