# Generated by Django 5.0.4 on 2025-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.FloatField(
                        default=1,
                        help_text="length of the cargo bed in centimeters",
                        verbose_name="Length",
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        default=1,
                        help_text="width  of the cargo bed in centimeters",
                        verbose_name="Width",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=1,
                        help_text="height of the cargo bed in centimeters",
                        verbose_name="Height",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1,
                        help_text="Gross Vehicle Weight in Kilograms",
                        verbose_name="Weight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Total Distance",
                    ),
                ),
                (
                    "total_duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Total Duration",
                    ),
                ),
                (
                    "transport_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Transport Distance",
                    ),
                ),
                (
                    "transport_duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Transport Duration",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "collection_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Collection Date"
                    ),
                ),
                (
                    "collection_address",
                    models.CharField(
                        default="AZM",
                        help_text="Collection address",
                        max_length=100,
                        verbose_name="Collection Address",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        default="AZM",
                        help_text="Delivery address",
                        max_length=100,
                        verbose_name="Delivery Address",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="About cargo, loading and unloading place",
                        max_length=900,
                        null=True,
                        verbose_name="Additional information",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pending quotation"),
                            (1, "Pending your acceptance"),
                            (2, "Accepted"),
                            (3, "In progress"),
                            (4, "Completed"),
                            (5, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
    ]
