# Generated by Django 5.0.4 on 2025-09-16 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.employee"
            ),
        ),
        migrations.AddField(
            model_name="cargodimension",
            name="transport",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimensions",
                to="transport.transport",
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="transportstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="cargo_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transport.transportstatus",
            ),
        ),
    ]
