# Generated by Django 5.0.4 on 2025-10-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_initial"),
        ("users", "0004_alter_department_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
            ),
        ),
    ]
