# Generated by Django 5.0.4 on 2025-10-03 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transports", "0002_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePriceModificator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Tractor", "Tractor"),
                            ("Solo", "Solo Truck"),
                            ("Semi-trailer", "Semi-trailer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Value of modificator for base price tag of solo-truck transport.",
                        max_digits=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kilometer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.2,
                        help_text="Kilograms",
                        max_digits=6,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "toll_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Toll Fee",
                        max_digits=6,
                        verbose_name="Toll Fee",
                    ),
                ),
                (
                    "fuel_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        default=16.0,
                        help_text="Fuel rate for 100 kilometers ",
                        max_digits=6,
                    ),
                ),
                (
                    "driver_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.9,
                        help_text="Driver rate per kilometer",
                        max_digits=6,
                    ),
                ),
                (
                    "maintenance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Truck maintenance cost per transport",
                        max_digits=6,
                    ),
                ),
                (
                    "minimal_profit",
                    models.IntegerField(
                        default=100, help_text="Minimal profit for this transport"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for this transport with profit",
                        max_digits=6,
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transports.transport",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
