# Generated by Django 5.0.4 on 2025-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepricemodificator",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("tractor", "Tractor"),
                    ("solo_truck", "Solo Truck"),
                    ("semi_trailer", "Semi-trailer"),
                ],
                max_length=30,
            ),
        ),
    ]
