# Generated by Django 5.0.4 on 2025-10-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0002_alter_basepricemodificator_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Total price for this transport with profit",
                max_digits=6,
            ),
        ),
    ]
