# Generated by Django 5.0.4 on 2025-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0003_alter_quotation_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1100,
                help_text="Total price for this transport with profit",
                max_digits=6,
            ),
        ),
    ]
