# Generated by Django 5.0.4 on 2025-11-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0004_alter_quotation_total_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BasePriceModificator",
            new_name="VehiclePriceModificator",
        ),
    ]
