# Generated by Django 5.0.4 on 2025-10-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        ("transports", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="transport_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transports.transport",
            ),
        ),
    ]
