# Generated by Django 5.0.4 on 2025-10-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_transport_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="transport_status",
            new_name="transport",
        ),
    ]
