# Generated by Django 5.0.4 on 2025-08-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="notes",
        ),
    ]
