# Generated by Django 5.0.4 on 2025-11-02 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_rename_transport_status_notification_transport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="transport",
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
